---
dependency:
  name: galaxy
driver:
  name: docker
lint:
  name: yamllint
platforms:
  - name: instance
    image: ubuntu
    image_version: xenial
provisioner:
  name: ansible
  lint:
    name: ansible-lint
scenario:
  name: default
  test_sequence:
    - destroy
    - create
    - converge
    # Disabled idempotence check--in this role, Molecule seems to return some
    # false positives.
    # - idempotence
    - lint
    - verify
verifier:
  name: testinfra
  lint:
    name: flake8
