---
# link tasks for ansible-role-files.

- name: Ensure required links exist.
  file:
    src: "{{ file.src }}"
    dest: "{{ file.dest }}"
    owner: "{{ file.owner | default(omit) }}"
    group: "{{ file.group | default(omit) }}"
    mode: "{{ file.mode | default(omit) }}"
    state: "{{ file.state }}"
    force: "{{ file.force | default(omit) }}"
